### ISSUE TITLE
.suo, .user, bin, debug should not be commited to Git

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Basket#1]
Files `.suo` and `.user`, folders `bin`, `debug` should not be commited to Git.

See: http://stackoverflow.com/questions/72298/should-i-add-the-visual-studio-suo-and-user-files-to-source-control

You may use the .gitignore file, which is used in all StarcounterSamples: https://github.com/StarcounterSamples/Polyjuice/wiki/.gitignore

**Comment by jakubklekota** [comment]
Thanks, files with this extensions was deleted.

**Comment by warpech** [comment]
I forgot to mention: `obj`

**Comment by jakubklekota** [comment]
@warpech now it's correct ?

**Comment by warpech** [comment]
Yes, except that `.gitignore` should be in the project root. Otherwise, the file `BasketDemo.v12.suo` can get accidentally commited again.

**Comment by jakubklekota** [comment]
fixed

**Comment by warpech** [comment]
Thx!
