### ISSUE TITLE
Main page need product application to working

### ISSUE THREAD

**Issue by aloscha** [handsoncode-apps/Basket#19]
In current version, we need to host product application to make some operation of element. So if product app doesn't run we see no products available to buy.

On the other hand price column. @warpech what do you think with that? How it could be configurable and from where?

![image](https://cloud.githubusercontent.com/assets/5141943/15899513/4aea9ec0-2d9c-11e6-9499-8daa64988ff6.png)

**Comment by warpech** [comment]
Right now:

- The products are created in the Products app (using Simplified data model)
- The prices are created in the Barcodes app, which enhances the product view in the Products app

So if you are running Products + Barcodes, you can define product items with prices.

In [EpicDemo](https://github.com/Starcounter/EpicDemo) this will change to something more flexible (but still comparable).
