### ISSUE TITLE
BrainTree it's the payment provider - what this title means?

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/Basket#6]

**Comment by jakubklekota** [comment]
@miyconst in future if will more than one payment provider, user can choose, which payment provider can pay.

**Comment by miyconst** [comment]
I still don't get the idea of the title. User will click on the Pay button of the provider he/she likes, why need the title, especially when there is only one payment method?

**Comment by jakubklekota** [comment]
Currently it is only one payment provider - BrainTree, but in the future, if there will be more than one payment provider, the user will be able to choose the one that suits him best.

If creating in future next payment provider like Paypal, and install form starcounter AppStore, in basket app view show radiobutton list with payment provider. One client choose paypal, the second braintree, and then click the pay button which redirect to payment details,

It's only idea.
Look:
https://www.softcall.me/UserFiles/Image/031-choose_your_payment_method_and_proceed.png

**Comment by warpech** [comment]
The text in the readme was changed. Closing.

More information is in Requirements (https://github.com/handsoncode-apps/Basket/issues/13). Will be added to README.md at a later point
