### ISSUE TITLE
The app does not build

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Basket#8]
The app does not build, with the error being:

> The type or namespace name 'Payable' could not be found (are you missing a using directive or an assembly reference?)	Basket	c:\www\handsoncode-apps\BasketDemoApp\Basket\obj\x64\Debug\ViewModels\Basket\BasketViewPage.json.g.cs	89

I guess this is because it was not adapted to the last change in Simplified or a change to Basket was not pushed

**Comment by jakubklekota** [comment]
@warpech fixed

**Comment by warpech** [comment]
Builds now :) Closing
